# -*- coding: utf-8 -*-
"""data_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_TTaiQ7HvlESUWAoEL_-b5F_pbVMEjB
"""



import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



missing_values = customers_df.isnull().sum()
display(missing_values)

customers_df = pd.read_csv('/content/customers.csv')
display(customers_df.head())



offers_df = pd.read_csv('/content/offers.csv')
display(offers_df.head())

# Convert 'became_member_on' to datetime and extract year and month
customers_df['became_member_on'] = pd.to_datetime(customers_df['became_member_on'], format='%Y%m%d')
customers_df['became_member_year'] = customers_df['became_member_on'].dt.year
customers_df['became_member_month'] = customers_df['became_member_on'].dt.month
display(customers_df[['became_member_on', 'became_member_year', 'became_member_month']].head())

print('--- customers_df.head() ---')
display(customers_df.head())

print('\n--- offers_df.head() ---')
display(offers_df.head())

print('\n--- dim_date_df.head() ---')
display(dim_date_df.head())

print('\n--- fact_transactions_df.head() ---')
display(fact_transactions_df.head())

print('\n--- fact_offer_events_df.head() ---')
display(fact_offer_events_df.head())

print('\n--- bridge_customer_offer_df.head() ---')
display(bridge_customer_offer_df.head())

print('\n--- events_df.head() ---')
display(events_df.head())

print('\n--- received_offers.head() ---')
display(received_offers.head())

print('\n--- viewed_offers.head() ---')
display(viewed_offers.head())

print('\n--- completed_offers.head() ---')
display(completed_offers.head())

# 1. Total Revenue (same as Total Sales already calculated)
print(f"Total Revenue: ${total_sales:.2f}")

# 2. Total Transactions
total_transactions = fact_transactions_df.shape[0]
print(f"Total Transactions: {total_transactions}")

# 3. Avg Transaction Value
avg_transaction_value = total_sales / total_transactions
print(f"Average Transaction Value: ${avg_transaction_value:.2f}")

# 4. Active Customers
active_customers = customers_df['customer_id'].nunique()
print(f"Active Customers: {active_customers}")

# 5. Offers Received
total_offers_received = bridge_customer_offer_df['times_received'].sum()
print(f"Total Offers Received: {total_offers_received}")

# 6. Offers Viewed
total_offers_viewed = bridge_customer_offer_df['times_viewed'].sum()
print(f"Total Offers Viewed: {total_offers_viewed}")

# 7. Offers Completed
total_offers_completed = bridge_customer_offer_df['times_completed'].sum()
print(f"Total Offers Completed: {total_offers_completed}")

# 8. View Rate %
view_rate_pct = (total_offers_viewed / total_offers_received) * 100 if total_offers_received > 0 else 0
print(f"View Rate: {view_rate_pct:.2f}%")

# 9. Completion Rate %
completion_rate_pct = (total_offers_completed / total_offers_received) * 100 if total_offers_received > 0 else 0
print(f"Completion Rate: {completion_rate_pct:.2f}%")

# 10. Revenue per Customer
revenue_per_customer = total_sales / active_customers
print(f"Revenue per Customer: ${revenue_per_customer:.2f}")

# 11. BOGO Completed
bogo_completed_df = bridge_customer_offer_df.merge(offers_df[offers_df['offer_type'] == 'bogo'], on='offer_id', how='inner')
total_bogo_completed = bogo_completed_df['times_completed'].sum()
print(f"BOGO Offers Completed: {total_bogo_completed}")

# 12. Discount Completed
discount_completed_df = bridge_customer_offer_df.merge(offers_df[offers_df['offer_type'] == 'discount'], on='offer_id', how='inner')
total_discount_completed = discount_completed_df['times_completed'].sum()
print(f"Discount Offers Completed: {total_discount_completed}")

# 13. Converted Customers (customers who completed at least one offer)
converted_customers = bridge_customer_offer_df[bridge_customer_offer_df['converted'] == 1]['customer_id'].nunique()
print(f"Converted Customers: {converted_customers}")

# 14. Conversion Rate % (unique customers who completed at least one offer / unique customers who received at least one offer)
customers_received_offers = bridge_customer_offer_df['customer_id'].nunique()
conversion_rate_customers_pct = (converted_customers / customers_received_offers) * 100 if customers_received_offers > 0 else 0
print(f"Customer Conversion Rate: {conversion_rate_customers_pct:.2f}%")

# 15. Revenue (Female)
female_revenue_df = fact_transactions_df.merge(customers_df[customers_df['gender'] == 'F'], on='customer_id', how='inner')
revenue_female = female_revenue_df['amount'].sum()
print(f"Revenue (Female): ${revenue_female:.2f}")

# 16. Revenue (Male)
male_revenue_df = fact_transactions_df.merge(customers_df[customers_df['gender'] == 'M'], on='customer_id', how='inner')
revenue_male = male_revenue_df['amount'].sum()
print(f"Revenue (Male): ${revenue_male:.2f}")

# 17. Daily Revenue Avg
unique_days = fact_transactions_df['day'].nunique()
daily_revenue_avg = total_sales / unique_days
print(f"Daily Revenue Average: ${daily_revenue_avg:.2f}")

print('\n--- dim_date_df.head() ---')
display(dim_date_df.head())

print('\n--- fact_transactions_df.head() ---')
display(fact_transactions_df.head())

print('\n--- fact_offer_events_df.head() ---')
display(fact_offer_events_df.head())

print('\n--- bridge_customer_offer_df.head() ---')
display(bridge_customer_offer_df.head())

print('\n--- events_df.head() ---')
display(events_df.head())

print('\n--- received_offers.head() ---')
display(received_offers.head())

print('\n--- viewed_offers.head() ---')
display(viewed_offers.head())

print('\n--- completed_offers.head() ---')
display(completed_offers.head())

# Calculate total sales
total_sales = fact_transactions_df['amount'].sum()
print(f"Total Sales: ${total_sales:.2f}")

# Calculate daily sales
daily_sales = fact_transactions_df.groupby('day')['amount'].sum().reset_index()
daily_sales.rename(columns={'amount': 'daily_total_sales'}, inplace=True)
print("\nDaily Sales:")
display(daily_sales.head())

# Calculate weekly sales
weekly_sales = fact_transactions_df.groupby('week')['amount'].sum().reset_index()
weekly_sales.rename(columns={'amount': 'weekly_total_sales'}, inplace=True)
print("\nWeekly Sales:")
display(weekly_sales.head())

display(customers_df.head())

customers_df.to_csv('customers_processed.csv', index=False)
offers_df.to_csv('offers_processed.csv', index=False)
dim_date_df.to_csv('dim_date_processed.csv', index=False)
fact_transactions_df.to_csv('fact_transactions_processed.csv', index=False)
fact_offer_events_df.to_csv('fact_offer_events_processed.csv', index=False)
bridge_customer_offer_df.to_csv('bridge_customer_offer_processed.csv', index=False)

print("All processed DataFrames have been saved to CSV files.")

# Replace age 118 with NaN (null) and fill gender nulls with 'Unknown'
customers_df['age'] = customers_df['age'].replace(118, np.nan)
customers_df['gender'] = customers_df['gender'].fillna('Unknown')
display(customers_df[['age', 'gender']].head())
display(customers_df.isnull().sum())

# Add 'age_group' column
age_bins = [0, 30, 45, 60, 75, 120]
age_labels = ['<30', '30-44', '45-59', '60-74', '75+']
customers_df['age_group'] = pd.cut(customers_df['age'], bins=age_bins, labels=age_labels, right=False)
display(customers_df['age_group'].value_counts(dropna=False))

# Add 'income_group' column
income_bins = [0, 40000, 60000, 80000, 120000, np.inf] # Using np.inf for the upper bound
income_labels = ['<40K', '40K-60K', '60K-80K', '80K-120K', '120K+']
customers_df['income_group'] = pd.cut(customers_df['income'], bins=income_bins, labels=income_labels, right=False)
display(customers_df['income_group'].value_counts(dropna=False))

import ast

# Parse channels column
offers_df['channels_parsed'] = offers_df['channels'].apply(lambda x: ast.literal_eval(x))

# Create binary columns for each channel
offers_df['has_email'] = offers_df['channels_parsed'].apply(lambda x: 1 if 'email' in x else 0)
offers_df['has_mobile'] = offers_df['channels_parsed'].apply(lambda x: 1 if 'mobile' in x else 0)
offers_df['has_social'] = offers_df['channels_parsed'].apply(lambda x: 1 if 'social' in x else 0)
offers_df['has_web'] = offers_df['channels_parsed'].apply(lambda x: 1 if 'web' in x else 0)

# Count channels
offers_df['channel_count'] = offers_df['channels_parsed'].apply(lambda x: len(x))

# Compute roi_pct, handling division by zero
offers_df['roi_pct'] = offers_df.apply(lambda row: (row['reward'] / row['difficulty']) * 100 if row['difficulty'] != 0 else np.nan, axis=1)

# Drop the original channels string column and the intermediate parsed column
offers_df = offers_df.drop(columns=['channels', 'channels_parsed'])

display(offers_df.head())





import ast

# Load events.csv
events_df = pd.read_csv('/content/events.csv')

# Filter for transaction events
fact_transactions_df = events_df[events_df['event'] == 'transaction'].copy()

# Parse the 'value' column to extract 'amount'
fact_transactions_df['value_parsed'] = fact_transactions_df['value'].apply(lambda x: ast.literal_eval(x))
fact_transactions_df['amount'] = fact_transactions_df['value_parsed'].apply(lambda x: x.get('amount'))

# Derive 'day' and 'week' from the 'time' column
fact_transactions_df['day'] = fact_transactions_df['time'] // 24
fact_transactions_df['week'] = fact_transactions_df['time'] // (24 * 7)

# Rename 'time' to 'hour' for clarity as per description
fact_transactions_df.rename(columns={'time': 'hour'}, inplace=True)

# Select the final columns
fact_transactions_df = fact_transactions_df[['customer_id', 'hour', 'day', 'week', 'amount']]

display(fact_transactions_df.head())

# Create dim_date DataFrame from scratch
dim_date_df = pd.DataFrame({'day': range(30)})

# Derive 'week' column
dim_date_df['week'] = dim_date_df['day'] // 7 + 1

# Derive 'day_label' column
dim_date_df['day_label'] = dim_date_df['day'].apply(lambda x: f"Day {x}")

# Derive 'week_label' column
dim_date_df['week_label'] = dim_date_df['week'].apply(lambda x: f"Week {x}")

display(dim_date_df.head())



# Calculate times_received, times_viewed, and times_completed
received_offers = fact_offer_events_df[fact_offer_events_df['event_type'] == 'offer received'].groupby(['customer_id', 'offer_id']).size().reset_index(name='times_received')
viewed_offers = fact_offer_events_df[fact_offer_events_df['event_type'] == 'offer viewed'].groupby(['customer_id', 'offer_id']).size().reset_index(name='times_viewed')
completed_offers = fact_offer_events_df[fact_offer_events_df['event_type'] == 'offer completed'].groupby(['customer_id', 'offer_id']).size().reset_index(name='times_completed')

# Merge the counts together
bridge_customer_offer_df = received_offers \
                           .merge(viewed_offers, on=['customer_id', 'offer_id'], how='outer') \
                           .merge(completed_offers, on=['customer_id', 'offer_id'], how='outer')

# Fill NaN values (where an event didn't occur) with 0
bridge_customer_offer_df = bridge_customer_offer_df.fillna(0)

# Add 'converted' column
bridge_customer_offer_df['converted'] = (bridge_customer_offer_df['times_completed'] >= 1).astype(int)

display(bridge_customer_offer_df.head())

import ast

# Filter for offer-related events
offer_events = ['offer received', 'offer viewed', 'offer completed']
fact_offer_events_df = events_df[events_df['event'].isin(offer_events)].copy()

# Parse the 'value' column to extract 'offer_id' and 'reward_earned'
fact_offer_events_df['value_parsed'] = fact_offer_events_df['value'].apply(lambda x: ast.literal_eval(x))
fact_offer_events_df['offer_id'] = fact_offer_events_df['value_parsed'].apply(lambda x: x.get('offer id', x.get('offer_id', None)))
fact_offer_events_df['reward_earned'] = fact_offer_events_df['value_parsed'].apply(lambda x: x.get('reward', None))

# Derive 'day' from the 'time' column
fact_offer_events_df['day'] = fact_offer_events_df['time'] // 24

# Rename 'time' to 'hour'
fact_offer_events_df.rename(columns={'time': 'hour', 'event': 'event_type'}, inplace=True)

# Select the final columns
fact_offer_events_df = fact_offer_events_df[['customer_id', 'event_type', 'offer_id', 'reward_earned', 'hour', 'day']]

display(fact_offer_events_df.head())



